# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85dafb56dace965a1f2e63b26faa97ff77bfad57dd53afec0b48dd3414cabc48d3515da92c8ad47ca324fd4412cd70ed21784a7b0fdfeb7834168083066d3df1

test:
  secret_key_base: 2edee03593f079e3a9e1963450de80255d66c36525107a27f5f4522109308ad37176544afbc04e4d92fbe2f10dff001b8bfcdf39bd3945f56df5d81afaf1dd93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
